### ISSUE TITLE
Element after shadow pseudo-selector isn't correctly scoped

### ISSUE THREAD

**Issue by burodepeper** [burodepeper/minimal-syntax#4]
``` less
atom-text-editor,
:host {
  &::shadow {}
  background-color: @white;
}
```

Because the shadow pseudo-selector is there, background-color isn't correctly scoped.

![schermafbeelding 2015-08-23 om 16 19 03](https://cloud.githubusercontent.com/assets/3703530/9428558/b0a6d69e-49b2-11e5-9c51-1dbd0022146d.png)
